[package]
name = "yaqb"
version = "0.1.0"
authors = ["Sean Griffin <sean@thoughtbot.com>"]

[dependencies]
libc = "*"
pq-sys = "0.1.*"
byteorder = "0.3.*"

[dev-dependencies]
compiletest_rs = "*"

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
harness = true

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
