[package]
name = "yaqb"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
libc = "0.2.*"
pq-sys = "0.2.*"
byteorder = "0.3.*"

[dev-dependencies]
quickcheck = "*"
dotenv = "0.4.0"
