[package]
name = "diesel_demo_step_1_pg"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_infer_schema = { path = "../../../diesel_infer_schema/", version = "0.16.0", features = ["postgres"] }
dotenv = "0.10"
