[package]
name = "diesel_migrations"
version = "1.0.0.beta1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Migratation managment for diesel"
documentation = "https://docs.rs/crate/diesel_migrations"
homepage = "http://diesel.rs"


[dependencies]
clippy = { optional = true, version = "=0.0.174" }
migrations_internals = { version = "1.0.0.beta1" }
migrations_macros = { version = "1.0.0.beta1" }

[dev-dependencies]
diesel = { version = "1.0.0.beta1", features = ["sqlite", "postgres", "mysql"] }
dotenv = ">=0.8, <0.11"
cfg-if = "0.1.0"

[features]
default = []
lint = ["clippy"]
sqlite = []
postgres = []
mysql = []
