[package]
name = "diesel"
version = "0.9.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "A safe, extensible ORM and Query builder"
documentation = "http://docs.diesel.rs"
homepage = "http://diesel.rs"
repository = "https://github.com/diesel-rs/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]
categories = ["database"]

[dependencies]
libc = "0.2.*"
pq-sys = { version = "^0.2.0", optional = true }
libsqlite3-sys = { version = "^0.4.0", optional = true }
byteorder = "0.3.*"
quickcheck = { version = "0.3.1", optional = true }
chrono = { version = "^0.2.17", optional = true }
uuid = { version = ">=0.2.0, <0.4.0", optional = true, features = ["use_std"] }
serde_json = { version = ">=0.8.0, <0.10.0", optional = true }

[dev-dependencies]
diesel_codegen = "0.9.0"
quickcheck = "0.3.1"
dotenv = "0.8.0"
tempdir = "^0.3.4"

[features]
default = ["with-deprecated"]
unstable = []
large-tables = []
huge-tables = ["large-tables"]
postgres = ["pq-sys"]
sqlite = ["libsqlite3-sys"]
with-deprecated = []
