[package]
name = "diesel"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
description = "A safe, extensible ORM and Query builder"
documentation = "http://sgrif.github.io/diesel/diesel/index.html"
homepage = "https://github.com/sgrif/diesel"
repository = "https://github.com/sgrif/diesel"

[dependencies]
libc = "0.2.*"
pq-sys = "0.2.*"
byteorder = "0.3.*"

[dev-dependencies]
quickcheck = "*"
dotenv = "0.4.0"

[features]
unstable = []
nightly = []
