[package]
name = "diesel"
version = "0.2.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
description = "A safe, extensible ORM and Query builder"
documentation = "http://sgrif.github.io/diesel/diesel/index.html"
homepage = "https://github.com/sgrif/diesel"
repository = "https://github.com/sgrif/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]

[dependencies]
libc = "0.2.*"
pq-sys = "0.2.*"
byteorder = "0.3.*"
quickcheck = { git = "https://github.com/sgrif/quickcheck.git", rev = "7020692b18196d9d29718b31d8b2c7d1c4df3190", optional = true }

[dev-dependencies]
quickcheck = { git = "https://github.com/sgrif/quickcheck.git", rev = "7020692b18196d9d29718b31d8b2c7d1c4df3190" }
dotenv = "^0.6.0"

[features]
unstable = []
