[package]
name = "diesel"
version = "0.2.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
description = "A safe, extensible ORM and Query builder"
documentation = "http://sgrif.github.io/diesel/diesel/index.html"
homepage = "https://github.com/sgrif/diesel"
repository = "https://github.com/sgrif/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]

[dependencies]
libc = "0.2.*"
pq-sys = "0.2.*"
byteorder = "0.3.*"
quickcheck = { version = "^0.2.24", optional = true }

[dev-dependencies]
quickcheck = "^0.2.24"
dotenv = "0.4.0"

[features]
unstable = []
