[package]
name = "diesel_demo_step_1"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = "0.8.2"
diesel_codegen = { version = "0.8.2", features = ["postgres"] }
dotenv = "0.8.0"
