[package]
name = "diesel_compile_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[workspace]

[dependencies]
diesel = { version = "0.99.0", features = ["extras", "sqlite", "postgres", "mysql"] }
compiletest_rs = "=0.3.3"

[replace]
"diesel:0.99.0" = { path = "../diesel" }
"diesel_derives:0.99.0" = { path = "../diesel_derives" }
