[package]
name = "diesel_compile_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[workspace]

[dependencies]
diesel = { version = "1.0.0-beta1", features = ["extras", "sqlite", "postgres", "mysql"] }
compiletest_rs = "=0.3.3"

[replace]
"diesel:1.0.0-beta1" = { path = "../diesel" }
"diesel_derives:1.0.0-beta1" = { path = "../diesel_derives" }
