[package]
name = "diesel_compile_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { path = "../diesel", features = ["sqlite", "postgres"] }
diesel_codegen = { path = "../diesel_codegen", features = ["postgres", "sqlite"] }
compiletest_rs = "0.2.0"
