[package]
name = "migrations_internals"
version = "0.99.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Internal implementation of diesels migration mechanism"
homepage = "http://diesel.rs"

[dependencies]
clippy = { optional = true, version = "=0.0.162" }
diesel = "0.99.0"

[dev-dependencies]
tempdir = "0.3.4"

[features]
default = []
lint = ["clippy"]
