[package]
name = "migrations_internals"
version = "2.0.0-rc.1"
license = "MIT OR Apache-2.0"
description = "Internal implementation of diesels migration mechanism"
homepage = "https://diesel.rs"
rust-version = "1.56.0"

[dependencies]
serde = {version = "1", features = ["derive"]}
toml = "0.5"

