[package]
name = "diesel_cli"
version = "0.4.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
description = "Provides the CLI for the Diesel crate"
documentation = "http://sgrif.github.io/diesel/diesel/index.html"
homepage = "https://github.com/sgrif/diesel"
repository = "https://github.com/sgrif/diesel"
keywords = ["orm", "database", "postgres", "postgresql", "sql"]

[[bin]]
name = "diesel"

[dependencies]
chrono = "^0.2.17"
clap = "^1.5.5"
diesel = { path = "../diesel", features = ["postgres", "sqlite"] }
dotenv = "^0.8.0"

[dev-dependencies]
tempdir = "^0.3.4"

[features]
postgres = ["diesel/postgres"]
sqlite = ["diesel/sqlite"]
