[package]
name = "diesel_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
syntex = { version = "0.38.0", optional = true }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
dotenv_codegen = { version = "0.9.0",  optional = true }
diesel = { path = "../diesel", default-features = false }
dotenv = { git = "https://github.com/slapresta/rust-dotenv.git" }

[dependencies]
assert_matches = "1.0.1"
chrono = { version = "^0.2.17" }
diesel = { path = "../diesel", default-features = false, features = ["quickcheck", "chrono", "uuid"] }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
dotenv_macros = { version = "0.9.0", optional = true }
quickcheck = "0.2.25"
uuid = { version = "^0.2.0" }

[features]
default = ["with-syntex"]
unstable = ["diesel_codegen/nightly", "diesel/unstable", "dotenv_macros"]
with-syntex = ["syntex", "dotenv_codegen", "diesel_codegen/with-syntex"]
postgres = ["diesel/postgres", "diesel_codegen/postgres"]
sqlite = ["diesel/sqlite", "diesel_codegen/sqlite"]

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
