[package]
name = "diesel_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
build = "build.rs"

[build-dependencies]
syntex = { version = "^0.22.0", optional = true }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
dotenv_codegen = { git = "https://github.com/mcasper/rust-dotenv", rev = "a12e8e097681ef5a398c652f8ff6f041502cd729",  optional = true }
diesel = { path = "../diesel" }
dotenv = "^0.7.0"

[dependencies]
diesel = { path = "../diesel", features = ["quickcheck"] }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
compiletest_rs = { version = "^0.0.10", optional = true }
dotenv_macros = { version = "^0.7.0", optional = true }

[dev-dependencies]
quickcheck = { git = "https://github.com/BurntSushi/quickcheck.git" }

[features]
default = ["syntex", "diesel_codegen/with-syntex", "dotenv_codegen"]
unstable = ["compiletest_rs", "diesel_codegen/nightly", "diesel/unstable",
  "quickcheck/unstable", "dotenv_macros"]

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
harness = true

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
