[package]
name = "diesel_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
build = "build.rs"

[build-dependencies]
quasi_codegen = { verision = "^0.3.8", optional = true }
syntex = { version = "^0.22.0", optional = true }
diesel_codegen = { path = "../diesel_codegen", default-features = false }

[dependencies]
diesel = { path = "../diesel", features = ["quickcheck"] }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
compiletest_rs = { version = "^0.0.10", optional = true }
syntex = { version = "^0.22.0", optional = true }
syntex_syntax = { version = "^0.22.0", optional = true }

[dev-dependencies]
quickcheck = "*"
dotenv = "0.4.0"

[features]
default = ["syntex", "syntex_syntax", "diesel_codegen/with-syntex"]
unstable = ["compiletest_rs", "diesel_codegen/nightly"]

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
harness = true

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
