[package]
name = "diesel_tests"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"

[build-dependencies]
syntex = { version = "^0.26.0", optional = true }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
dotenv_codegen = { git = "https://github.com/slapresta/rust-dotenv.git",  optional = true }
diesel = { path = "../diesel" }
dotenv = { git = "https://github.com/slapresta/rust-dotenv.git" }

[dependencies]
diesel = { path = "../diesel", features = ["quickcheck", "chrono"] }
diesel_codegen = { path = "../diesel_codegen", default-features = false }
compiletest_rs = { version = "^0.0.11", optional = true }
dotenv_macros = { git = "https://github.com/slapresta/rust-dotenv.git", optional = true }
chrono = { version = "^0.2.17" }

[dev-dependencies]
quickcheck = { git = "https://github.com/BurntSushi/quickcheck.git" }

[features]
default = ["syntex", "diesel_codegen/with-syntex", "dotenv_codegen"]
unstable = ["compiletest_rs", "diesel_codegen/nightly", "diesel/unstable",
  "quickcheck/unstable", "dotenv_macros"]
postgres = []
sqlite = []

[[test]]
name = "compile_tests"
path = "tests/compile_tests.rs"
harness = true

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[[bench]]
name = "benchmarks"
path = "tests/bench.rs"
bench = true
