[package]
name = "diesel_demo_step_2_pg"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "1.0.0.beta1", features = ["postgres"] }
diesel_infer_schema = { version = "1.0.0.beta1", features = ["postgres"] }
dotenv = "0.10"
