[package]
name = "diesel_demo_step_3_mysql"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "0.16.0", features = ["mysql"] }
diesel_proc_macro = { path = "../../../diesel_proc_macro", version = "0.16.0", features = ["mysql"] }
dotenv = "0.10"
