[package]
name = "diesel_codegen"
version = "0.2.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT"
build = "build.rs"
description = "Annotations to remove boilerplate from Diesel"
documentation = "https://github.com/sgrif/diesel/blob/master/diesel_codegen/README.md"
homepage = "https://github.com/sgrif/diesel/tree/master/diesel_codegen"
repository = "https://github.com/sgrif/diesel/tree/master/diesel_codegen"
keywords = ["orm", "database", "postgres", "sql", "codegen"]

[build-dependencies]
quasi_codegen = { verision = "^0.3.8", optional = true }
syntex = { version = "^0.22.0", optional = true }

[dependencies]
aster = { version = "^0.8.0", default-features = false }
quasi = { verision = "^0.3.8", default-features = false }
quasi_macros = { version = "^0.3.9", optional = true}
syntex = { version = "^0.22.0", optional = true }
syntex_syntax = { version = "^0.22.0", optional = true }

[features]
default = ["with-syntex"]
nightly = ["quasi_macros"]
with-syntex = ["quasi/with-syntex", "quasi_codegen", "quasi_codegen/with-syntex", "syntex", "syntex_syntax"]

[lib]
name = "diesel_codegen"
plugin = true
