[package]
name = "diesel_codegen"
version = "0.4.1"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]
license = "MIT OR Apache-2.0"
build = "build.rs"
description = "Annotations to remove boilerplate from Diesel"
documentation = "https://github.com/sgrif/diesel/blob/master/diesel_codegen/README.md"
homepage = "https://github.com/sgrif/diesel/tree/master/diesel_codegen"
repository = "https://github.com/sgrif/diesel/tree/master/diesel_codegen"
keywords = ["orm", "database", "postgres", "sql", "codegen"]

[build-dependencies]
quasi_codegen = { version = "^0.4.0", optional = true }
syntex = { version = "^0.26.0", optional = true }

[dependencies]
aster = { version = "^0.10.0", default-features = false }
quasi = { version = "^0.4.0", default-features = false }
quasi_macros = { version = "^0.4.0", optional = true}
syntex = { version = "^0.26.0", optional = true }
syntex_syntax = { version = "^0.26.0", optional = true }
diesel = { git = "https://github.com/sgrif/diesel.git" }

[features]
default = ["with-syntex"]
nightly = ["quasi_macros"]
with-syntex = ["quasi/with-syntex", "quasi_codegen", "quasi_codegen/with-syntex", "syntex", "syntex_syntax"]

[lib]
name = "diesel_codegen"
plugin = true
