[package]
name = "diesel_demo_step_1_mysql"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
diesel = { version = "0.99.0", features = ["mysql"] }
diesel_infer_schema = { version = "0.99.0", features = ["mysql"] }
dotenv = "0.10"
